services:
  - type: worker
    name: BalticPharmacyBot
    env: node
    branch: main
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    autoRestart: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false

      # --- Crypto Wallets (🔒 Bulletproof Wallet Routing)
      - key: BTC_WALLET
        sync: false
      - key: ETH_WALLET
        sync: false
      - key: SOL_WALLET
        sync: false
      - key: MATIC_WALLET
        sync: false

      # --- RPC Endpoints (💠 Chain Sync)
      - key: ETHEREUM_RPC
        sync: false
      - key: MATIC_RPC
        sync: false
      - key: SOLANA_RPC
        sync: false
      - key: BTC_RPC
        value: https://blockchain.info/q/addressbalance/
        sync: false

      # --- CoinGecko API (💶 EUR rates)
      - key: COINGECKO_URL
        value: https://api.coingecko.com/api/v3/simple/price
        sync: false

      # --- Feature Flags (🛡 System Logic)
      - key: AUTOBAN_ENABLED
        value: "true"
        sync: false
      - key: AUTODELETE_ENABLED
        value: "true"
        sync: false

      # --- Available Cities (📍 UX Layer)
      - key: CITIES
        value: Vilnius,Kaunas
        sync: false

  - type: worker
    name: CleanLogsWorker
    env: node
    branch: main
    runtime: node
    buildCommand: npm install
    startCommand: node cron/cleanOldLogs.js
    autoDeploy: false
    autoRestart: true
